name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: make deps

      - name: Pylint
        run: make check-lint

      - name: Run tests
        run: make test

      - name: Build executable
        run: make build

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: x-ray-linux-amd64
          path: dist/x-ray
